# Single source of truth: apps/mobile/package.json -> tauri.conf.json + Android tauri.properties
$ErrorActionPreference = "Stop"
$mobile = Split-Path -Parent $MyInvocation.MyCommand.Path
$pkgJson = Join-Path $mobile "package.json"
$tauriConf = Join-Path $mobile "src-tauri\tauri.conf.json"
$android = Join-Path $mobile "src-tauri\gen\android"
$tauriProps = Join-Path $android "app\tauri.properties"

$ver = (Get-Content $pkgJson -Raw | ConvertFrom-Json).version
$parts = $ver.Split(".")
if ($parts.Length -lt 3) { throw "package.json version must be semver (x.y.z), got $ver" }
$versionCode = ([int]$parts[0] * 10000) + ([int]$parts[1] * 100) + [int]$parts[2]

if (Test-Path $tauriConf) {
    $conf = Get-Content $tauriConf -Raw | ConvertFrom-Json
    if ($conf.version -ne $ver) {
        $conf.version = $ver
        $json = $conf | ConvertTo-Json -Depth 20
        [System.IO.File]::WriteAllText($tauriConf, $json + "`n", [System.Text.UTF8Encoding]::new($false))
        Write-Host "Synced tauri.conf.json version -> $ver" -ForegroundColor Green
    }
}

if (Test-Path $tauriProps) {
    @"
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
tauri.android.versionName=$ver
tauri.android.versionCode=$versionCode
"@ | Set-Content -Path $tauriProps -Encoding UTF8 -NoNewline
    Write-Host "Synced tauri.properties -> $ver (code $versionCode)" -ForegroundColor Green
}